/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardDriverRouteImport } from './routes/dashboard/driver'
import { Route as DashboardManagementRouteImport } from './routes/dashboard/management'
import { Route as DashboardUserRouteImport } from './routes/dashboard/user'
import { Route as DashboardVehicleOwnerRouteImport } from './routes/dashboard/vehicle-owner'
import { Route as SubscriptionIndexRouteImport } from './routes/subscription/index'
import { Route as SubscriptionReviewRouteImport } from './routes/subscription/review'
import { Route as SubscriptionSuccessRouteImport } from './routes/subscription/success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDriverRoute = DashboardDriverRouteImport.update({
  id: '/dashboard/driver',
  path: '/dashboard/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardManagementRoute = DashboardManagementRouteImport.update({
  id: '/dashboard/management',
  path: '/dashboard/management',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserRoute = DashboardUserRouteImport.update({
  id: '/dashboard/user',
  path: '/dashboard/user',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVehicleOwnerRoute = DashboardVehicleOwnerRouteImport.update({
  id: '/dashboard/vehicle-owner',
  path: '/dashboard/vehicle-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionIndexRoute = SubscriptionIndexRouteImport.update({
  id: '/subscription/',
  path: '/subscription/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionReviewRoute = SubscriptionReviewRouteImport.update({
  id: '/subscription/review',
  path: '/subscription/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionSuccessRoute = SubscriptionSuccessRouteImport.update({
  id: '/subscription/success',
  path: '/subscription/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plans': typeof PlansRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/management': typeof DashboardManagementRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/dashboard/vehicle-owner': typeof DashboardVehicleOwnerRoute
  '/subscription/review': typeof SubscriptionReviewRoute
  '/subscription/success': typeof SubscriptionSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/subscription/': typeof SubscriptionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans': typeof PlansRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/management': typeof DashboardManagementRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/dashboard/vehicle-owner': typeof DashboardVehicleOwnerRoute
  '/subscription/review': typeof SubscriptionReviewRoute
  '/subscription/success': typeof SubscriptionSuccessRoute
  '/dashboard': typeof DashboardIndexRoute
  '/subscription': typeof SubscriptionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plans': typeof PlansRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/management': typeof DashboardManagementRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/dashboard/vehicle-owner': typeof DashboardVehicleOwnerRoute
  '/subscription/review': typeof SubscriptionReviewRoute
  '/subscription/success': typeof SubscriptionSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/subscription/': typeof SubscriptionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plans'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/dashboard/management'
    | '/dashboard/user'
    | '/dashboard/vehicle-owner'
    | '/subscription/review'
    | '/subscription/success'
    | '/dashboard/'
    | '/subscription/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plans'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/dashboard/management'
    | '/dashboard/user'
    | '/dashboard/vehicle-owner'
    | '/subscription/review'
    | '/subscription/success'
    | '/dashboard'
    | '/subscription'
  id:
    | '__root__'
    | '/'
    | '/plans'
    | '/dashboard/admin'
    | '/dashboard/driver'
    | '/dashboard/management'
    | '/dashboard/user'
    | '/dashboard/vehicle-owner'
    | '/subscription/review'
    | '/subscription/success'
    | '/dashboard/'
    | '/subscription/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlansRoute: typeof PlansRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardDriverRoute: typeof DashboardDriverRoute
  DashboardManagementRoute: typeof DashboardManagementRoute
  DashboardUserRoute: typeof DashboardUserRoute
  DashboardVehicleOwnerRoute: typeof DashboardVehicleOwnerRoute
  SubscriptionReviewRoute: typeof SubscriptionReviewRoute
  SubscriptionSuccessRoute: typeof SubscriptionSuccessRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  SubscriptionIndexRoute: typeof SubscriptionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/driver': {
      id: '/dashboard/driver'
      path: '/dashboard/driver'
      fullPath: '/dashboard/driver'
      preLoaderRoute: typeof DashboardDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/management': {
      id: '/dashboard/management'
      path: '/dashboard/management'
      fullPath: '/dashboard/management'
      preLoaderRoute: typeof DashboardManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user': {
      id: '/dashboard/user'
      path: '/dashboard/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vehicle-owner': {
      id: '/dashboard/vehicle-owner'
      path: '/dashboard/vehicle-owner'
      fullPath: '/dashboard/vehicle-owner'
      preLoaderRoute: typeof DashboardVehicleOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/': {
      id: '/subscription/'
      path: '/subscription'
      fullPath: '/subscription/'
      preLoaderRoute: typeof SubscriptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/review': {
      id: '/subscription/review'
      path: '/subscription/review'
      fullPath: '/subscription/review'
      preLoaderRoute: typeof SubscriptionReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/success': {
      id: '/subscription/success'
      path: '/subscription/success'
      fullPath: '/subscription/success'
      preLoaderRoute: typeof SubscriptionSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlansRoute: PlansRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardDriverRoute: DashboardDriverRoute,
  DashboardManagementRoute: DashboardManagementRoute,
  DashboardUserRoute: DashboardUserRoute,
  DashboardVehicleOwnerRoute: DashboardVehicleOwnerRoute,
  SubscriptionReviewRoute: SubscriptionReviewRoute,
  SubscriptionSuccessRoute: SubscriptionSuccessRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  SubscriptionIndexRoute: SubscriptionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
